# experiment name
note: eval
# sub_sequence: 'sidehug'

#project basic
task: reconstruction

#model basic
gpu_index: 0
lr: 0.0001
batchsize: 32
epoch: 2000
worker: 0
use_sch: True
body_model: smpl
frame_length: 64
scale_factor: 1000.0
#********dataset*********#
# The path for datasets and annotations
data_folder: /root/autodl-fs/
output: /root/autodl-tmp/PW3D/out

trainset: PW3D
testset: PW3D

model: interhuman_diffusion_phys
smooth: False
use_classifier_guidance: False

mode: test # train/test/eval


# Use pretrain model and the corresponding path
pretrain: True
pretrain_dir: /root/autodl-tmp/Hi4D/out/refine64/05.01-19h33m30s/trained model/best_reconstruction_epoch006_30618980.000000.pkl
base_model: 0
# The name of your training loss function
# Split different names with a single space
# e.g., KL_Loss MPJPE L1 L2
train_loss: SMPL_Loss Keyp_Loss Mesh_Loss Joint_Loss Vel_Loss
test_loss: MPJPE MPVPE Int_Loss Vel_Loss SDF_Loss # Vel_Loss_Instance  # MPJPE MPVPE 

#visualize
viz: False
