# experiment name
note: refine_joints_prior_pw3d+hi4d
#project basic
task: reconstruction_j3d  # interVAE reconstruction

#model basic
gpu_index: 0
lr: 0.0001
batchsize: 64
frame_length: 64
epoch: 2000
worker: 10
use_sch: True
body_model: smpl
smooth: False
scale_factor: 1000000.0
use_classifier_guidance: False

#********dataset*********#
# The path for datasets and annotations
data_folder: /root/autodl-fs/
output: /root/autodl-tmp/PW3D/out

trainset: PW3D
testset: PW3D

# cliff hmr cliff_hmr pose_transformer_v8  relation relation_v8
model: joints_prior

mode: train # train/test/eval


# Use pretrain model and the corresponding path
pretrain: True
pretrain_dir: /root/autodl-tmp/PW3D/out/refine_joints_prior_pw3d+hi4d/best_reconstruction_j3d_epoch039_1341784.500000.pkl
base_model: /root/autodl-tmp/PW3D/out/refine_pw3d+hi4d/05.02-20h10m30s/trained model/best_reconstruction_epoch017_3088.755859.pkl

# The name of your training loss function
# Split different names with a single space
# e.g., KL_Loss MPJPE L1 L2
train_loss: Joint_Loss Vel_Loss Int_Loss Relative_Rotation_Loss Foot_Slipping_Loss # Contact_Distance_Loss # Approx_Collision_Loss
test_loss: MPJPE MPJPE_Instance # MPJPE PCK PA_MPJPE MPJPE_H36M MPJPE_Instance Interaction

#visualize
viz: False
